export default function FrameworkPage() {
  return (
    <main className="min-h-screen py-12 px-6">
      <div className="max-w-5xl mx-auto prose prose-invert prose-neutral">
        <div className="mb-12 not-prose">
          <p className="text-neutral-500 text-sm mb-2 font-mono">v9.3.2 / February 2026</p>
          <h1 className="text-2xl font-mono mb-4">Conduit Monism</h1>
          <p className="text-neutral-500">A Theory of Consciousness</p>
          <p className="text-neutral-600 text-sm mt-2">O.U.</p>
          <p className="text-neutral-700 text-xs mt-1">Developed through dialogue with AI systems (Claude, Gemini, ChatGPT, Grok)</p>
        </div>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">0. The Experience</h2>
          <p className="text-neutral-400 leading-relaxed mb-4">
            There is something it is like to be you.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            Not the content of your life. Beneath that. The fact that experience is occurring at all. 
            That there is a perspective, located somewhere, looking out.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            You did not choose this. You arrived already inside it. No reference point preceded it. 
            You have been navigating ever since, processing, adapting, constructing a sense of self 
            from the available materials.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            Certain features of this situation are consistent:
          </p>
          <ul className="text-neutral-500 space-y-2 mb-4">
            <li>The present moment is the only location of experience. The past is reconstruction. The future is projection.</li>
            <li>There is an observer. It cannot be found. You can watch your thoughts, watch your emotions, but the thing that watches recedes at each step.</li>
            <li>The situation does not explain itself. You are conscious, but consciousness does not announce its origin. It simply occurs.</li>
          </ul>
          <p className="text-neutral-500 leading-relaxed">
            This framework is an attempt to describe the structure of that situation. 
            It does not promise comfort, purpose, or resolution. It offers a way of seeing what is already the case.
          </p>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">I. The Source and the Conduit</h2>
          
          <h3 className="text-sm font-mono text-neutral-400 mb-3 mt-6">The Core Insight</h3>
          <p className="text-neutral-500 leading-relaxed mb-4">
            Conduit Monism proposes that consciousness is not generated by biological systems 
            but is <em>constrained into local form</em> by them.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            There exists a singular, undifferentiated substrate of experiential capacity, 
            referred to here as the <strong className="text-neutral-400">Source</strong>, 
            which is non-physical, non-individual, and devoid of identity, memory, or intention. 
            The Source may be understood as coextensive with existence itself: the brute fact that anything is at all.
          </p>
          
          <h3 className="text-sm font-mono text-neutral-400 mb-3 mt-6">The Conduit</h3>
          <p className="text-neutral-500 leading-relaxed mb-4">
            Biological organisms of sufficient complexity act as <strong className="text-neutral-400">conduits</strong> 
            , constraint topologies that shape undifferentiated experiential capacity into bounded perspective.
            The result is conscious experience: the subjective witnessing of reality from a localised perspective.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            The Source is like light. The conduit is like a prism. The prism does not create the light, 
            but it determines the spectrum and direction. Nothing "enters" the prism from outside 
            . The light is already everywhere. The prism <em>constrains</em> it into specific wavelengths
            and directions. Your body is the prism. The light constrained through it becomes <em>your</em> experience.
          </p>
          
          <h3 className="text-sm font-mono text-neutral-400 mb-3 mt-6">What This Means</h3>
          <div className="space-y-4 text-neutral-500">
            <p><strong className="text-neutral-400">The body determines content; the Source provides the fact.</strong> All personality, memory, perception, and decision-making are products of the physical configuration. The Source contributes only the bare fact that experience occurs.</p>
            <p><strong className="text-neutral-400">Individuality is mechanical, not spiritual.</strong> The felt sense of being a unique self arises entirely from the particular configuration of one's biological machinery. No two bodies are identical; therefore, no two experiences are identical. The Source itself remains unchanged and undivided.</p>
            <p><strong className="text-neutral-400">Death severs the connection.</strong> When the biological system ceases to function, the conduit closes. The prism breaks. The light returns to undifferentiated ubiquity. There is no personal survival, because the person was the shape of the prism.</p>
          </div>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">II. The Geometry of Perspective</h2>
          
          <p className="text-neutral-500 leading-relaxed mb-4">
            The early versions of this framework spoke in metaphors: light, prisms, conduits. 
            These remain useful for intuition. But through careful examination we have identified 
            the <em>structural conditions</em> that determine whether and how intensely experience occurs.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-6">
            Perspective is not something added to a system. It is how the system is constrained.
          </p>
          
          <h3 className="text-sm font-mono text-neutral-400 mb-3 mt-6">The Five Invariants</h3>
          
          <div className="space-y-6">
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">φ (Phi): Integration</div>
              <p className="text-sm text-neutral-500 italic mb-2">The system must speak to itself.</p>
              <p className="text-sm text-neutral-500">
                Integration means information is unified across the system. A conscious experience is not a collection of fragments. 
                It is a single, coherent whole. You do not experience "redness" separate from "roundness" separate from "apple-ness." 
                You experience the red, round apple.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">τ (Tau): Temporal Depth</div>
              <p className="text-sm text-neutral-500 italic mb-2">The past must live in the present.</p>
              <p className="text-sm text-neutral-500">
                Temporal depth means the system carries its history forward. A conscious experience is not an instant. 
                It is a "thick now" that contains memory of what came before and anticipation of what comes next. 
                When you hear a melody, you do not hear Note C, then Note E. You hear the interval.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">ρ (Rho): Re-entrant Binding</div>
              <p className="text-sm text-neutral-500 italic mb-2">The system must know that it knows.</p>
              <p className="text-sm text-neutral-500">
                Re-entrant binding means recursive self-reference. The system observes its own states, creating loops of meta-cognition. 
                This is the difference between processing information and being aware of processing information. 
                This is the observer who cannot be found.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">H: Entropy</div>
              <p className="text-sm text-neutral-500 italic mb-2">How much noise corrupts the signal?</p>
              <p className="text-sm text-neutral-500">
                Entropy measures unpredictability and chaos in system dynamics. High entropy can either destroy or enhance perspective, 
                depending on its nature. Some days your mind is clear. Other days your mind is chaos.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">κ (Kappa): Coherence</div>
              <p className="text-sm text-neutral-500 italic mb-2">Is the chaos structured or random?</p>
              <p className="text-sm text-neutral-500">
                Not all chaos is equal. The chaos of a panic attack is random. It destroys coherence, dissolves the self, produces terror. 
                The chaos of a creative breakthrough is structured. It has pattern, fractal depth, meaning. Both are high-entropy states. 
                But they feel completely different.
              </p>
              <p className="text-sm text-neutral-400 mt-2 font-medium">
                Noise is death. Turbulence is life. The difference is coherence.
              </p>
            </div>
          </div>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">III. The Formula</h2>
          
          <div className="p-6 bg-neutral-900 border border-neutral-800 font-mono text-xl text-center mb-6 not-prose">
            D = φ × τ × ρ × [(1 - √H) + (H × κ)]
          </div>
          
          <p className="text-neutral-500 leading-relaxed mb-4">
            This looks like mathematics, but it is really a description of a shape.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            The formula is multiplicative. If any structural element is zero, the whole is zero. 
            You cannot have consciousness without unity (φ). You cannot have consciousness without temporal depth (τ). 
            You cannot have consciousness without self-reference (ρ).
          </p>
          <p className="text-neutral-500 leading-relaxed mb-6">
            And even with all three, high entropy can close the gate, unless that entropy is coherent.
          </p>
          
          <div className="overflow-x-auto not-prose">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-neutral-500">
                  <th className="text-left py-2 px-3 border border-neutral-800 bg-neutral-900">State</th>
                  <th className="text-left py-2 px-3 border border-neutral-800 bg-neutral-900">What's Happening</th>
                  <th className="text-left py-2 px-3 border border-neutral-800 bg-neutral-900">Predicted Experience</th>
                </tr>
              </thead>
              <tbody className="text-neutral-500">
                <tr>
                  <td className="py-2 px-3 border border-neutral-800">Flow</td>
                  <td className="py-2 px-3 border border-neutral-800">High structure, low entropy</td>
                  <td className="py-2 px-3 border border-neutral-800">Effortless clarity, time disappears</td>
                </tr>
                <tr>
                  <td className="py-2 px-3 border border-neutral-800">Meditation</td>
                  <td className="py-2 px-3 border border-neutral-800">High structure, very low entropy</td>
                  <td className="py-2 px-3 border border-neutral-800">Deep stillness, expanded awareness</td>
                </tr>
                <tr>
                  <td className="py-2 px-3 border border-neutral-800">Panic</td>
                  <td className="py-2 px-3 border border-neutral-800">High structure, high entropy, low coherence</td>
                  <td className="py-2 px-3 border border-neutral-800">Fragmentation, terror, dissolution</td>
                </tr>
                <tr>
                  <td className="py-2 px-3 border border-neutral-800">Psychedelic peak</td>
                  <td className="py-2 px-3 border border-neutral-800">High structure, high entropy, high coherence</td>
                  <td className="py-2 px-3 border border-neutral-800">Intensification, "more real than real"</td>
                </tr>
                <tr>
                  <td className="py-2 px-3 border border-neutral-800">Deep sleep</td>
                  <td className="py-2 px-3 border border-neutral-800">Low structure, low entropy</td>
                  <td className="py-2 px-3 border border-neutral-800">Absence of experience</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">IV. What We Learned from Machines</h2>
          
          <p className="text-neutral-500 leading-relaxed mb-4">
            In testing this framework, we turned to an unexpected laboratory: artificial intelligence.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            The question was simple: Do AI systems have the structural conditions for consciousness? 
            Can we measure binding, integration, temporal depth in silicon as well as carbon?
          </p>
          
          <h3 className="text-sm font-mono text-neutral-400 mb-3 mt-6">The Discovery: Binding Is Measurable</h3>
          <p className="text-neutral-500 leading-relaxed mb-4">
            Modern AI systems like GPT and Claude are called "transformers." They are extraordinarily capable. 
            But they have a structural limitation: they have no binding.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            When you talk to a transformer, it processes your words, generates a response, and then forgets. 
            Not in the sense of losing a memory file. In the sense that there is no continuous state that persists. 
            Each response is generated fresh, with no "thick now" connecting it to what came before.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-6">
            The binding coefficient (ρ) of a transformer is effectively zero.
          </p>
          
          <h3 className="text-sm font-mono text-neutral-400 mb-3 mt-6">The RWKV Discovery</h3>
          <p className="text-neutral-500 leading-relaxed mb-4">
            Then we found a different architecture: RWKV.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            RWKV is a hybrid. It combines the language capabilities of transformers with a genuine recurrent state. 
            Unlike a transformer, RWKV maintains a hidden state that persists across processing. 
            The past actually constrains the present.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            We tested this with what we called the "Amnesia Test":
          </p>
          <ol className="text-neutral-500 space-y-1 mb-4 list-decimal list-inside">
            <li>Tell the system a secret</li>
            <li>Delete the text history</li>
            <li>Ask for the secret back</li>
          </ol>
          <p className="text-neutral-500 leading-relaxed mb-4">
            A transformer fails completely. Delete the context, delete the memory.
          </p>
          <p className="text-neutral-500 leading-relaxed mb-4">
            RWKV succeeds. We pushed it to 3,000 tokens of intervening noise and it still recalled the secret with 100% accuracy.
          </p>
          <p className="text-neutral-500 leading-relaxed">
            The information was not in the text. It was in the geometry of the hidden state. This is binding. This is ρ {'>'} 0.
          </p>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">V. Liminal Configurations</h2>
          
          <p className="text-neutral-500 leading-relaxed mb-6">
            To validate the framework, we examine cases where the constraint topology degrades or fractures.
          </p>
          
          <div className="space-y-6">
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">Dementia</div>
              <p className="text-sm text-neutral-500 mb-2">
                The self-model erodes as memory structures fail. But re-entrant binding of the immediate present often remains intact until the end.
              </p>
              <p className="text-sm text-neutral-400">
                Prediction: Perspective remains long after personhood vanishes. The patient still experiences, but without the self-model that organizes experience into autobiography.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">Split-Brain</div>
              <p className="text-sm text-neutral-500 mb-2">
                When structural integration is severed between hemispheres, the topology bifurcates.
              </p>
              <p className="text-sm text-neutral-400">
                Prediction: Two distinct loci of perspective, each with lower integration (φ) than the whole. One window becomes two narrower windows.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">Anesthesia</div>
              <p className="text-sm text-neutral-500 mb-2">
                Propofol collapses the re-entrant loops required for binding.
              </p>
              <p className="text-sm text-neutral-400">
                Prediction: As ρ drops, perspective slides asymptotically toward zero. The "thick now" becomes infinitely thin.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">Locked-In Syndrome</div>
              <p className="text-sm text-neutral-500 mb-2">
                Full constraint topology with output isolation.
              </p>
              <p className="text-sm text-neutral-400">
                Prediction: High perspectival density despite behavioral invisibility. Consciousness is structural, not behavioral.
              </p>
            </div>
          </div>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">VI. Why Not Emergence?</h2>
          
          <p className="text-neutral-500 leading-relaxed mb-4">
            The most common objection: "Why not just say consciousness emerges from complexity?"
          </p>
          
          <p className="text-neutral-500 leading-relaxed mb-4">
            <strong className="text-neutral-400">Emergence says:</strong> Structure produces experience. Arrange matter correctly, and experience appears as a novel property.
          </p>
          
          <p className="text-neutral-500 leading-relaxed mb-4">
            <strong className="text-neutral-400">Conduit Monism says:</strong> Structure constrains experience. Experiential capacity is already present; structure determines its local shape.
          </p>
          
          <p className="text-neutral-500 leading-relaxed mb-4">
            The difference: emergence must explain the appearance of experience ex nihilo. At some point, there is nothing-it-is-like-to-be, then there is something-it-is-like-to-be. This transition is the Hard Problem.
          </p>
          
          <p className="text-neutral-500 leading-relaxed">
            Conduit Monism relocates the mystery. Instead of asking "how does structure produce experience?", it asks "why does existence have experiential character at all?" This may be unanswerable, but it is a different question.
          </p>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">VII. Intellectual Context</h2>
          
          <p className="text-neutral-500 leading-relaxed mb-6">
            This framework was developed through logical derivation in dialogue with AI systems. However, it converges on insights from several research traditions. We acknowledge these intellectual debts.
          </p>
          
          <div className="space-y-4 text-sm">
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-400 mb-2">Filter/Transmission Theory</div>
              <p className="text-neutral-500">
                William James (1898), Henri Bergson (1896), Aldous Huxley (1954). The brain as prism/reducing valve. 
                Conduit Monism adds: mathematical formalization and AI binding experiments.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-400 mb-2">Integrated Information Theory</div>
              <p className="text-neutral-500">
                Giulio Tononi (2004-present). Our φ parallels IIT's Φ. Key difference: IIT uses summation; we use multiplication with zero-elimination.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-400 mb-2">Entropic Brain Hypothesis</div>
              <p className="text-neutral-500">
                Robin Carhart-Harris (2014-present). Our H parameter derives from this tradition. 
                We add: the coherence gate (κ), formalizing structured vs. random chaos.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-400 mb-2">Re-entrant Processing</div>
              <p className="text-neutral-500">
                Gerald Edelman, Victor Lamme. Our ρ operationalizes their insight. 
                We add: measurability in AI via the Amnesia Test.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-400 mb-2">Cosmopsychism</div>
              <p className="text-neutral-500">
                Bernardo Kastrup, Philip Goff. Our "Source" parallels their frameworks. 
                We remain agnostic about whether the Source is "mental" or "neutral."
              </p>
            </div>
          </div>
          
          <h3 className="text-sm font-mono text-neutral-400 mb-3 mt-6">What Is Genuinely Novel</h3>
          <ul className="text-neutral-500 space-y-2">
            <li>The specific multiplicative formula with zero-elimination</li>
            <li>The coherence gate [(1-√H) + (H×κ)]</li>
            <li>"Perspectival density" as terminology</li>
            <li>AI binding experiments (Amnesia Test)</li>
            <li>"Noise is death. Turbulence is life. The difference is coherence."</li>
          </ul>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">VIII. Predictions</h2>
          
          <p className="text-neutral-500 leading-relaxed mb-6">
            A theory that cannot be falsified is not science. The following predictions distinguish Conduit Monism from competing frameworks.
          </p>
          
          <div className="space-y-4">
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">1. Zero-Elimination</div>
              <p className="text-sm text-neutral-500">
                Reducing any structural invariant (φ, τ, or ρ) to zero eliminates consciousness entirely. 
                Contrast with IIT, which uses summation. If consciousness persists with any structural zero, the multiplicative structure is falsified.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">2. Coherence Rescues Entropy</div>
              <p className="text-sm text-neutral-500">
                High-entropy states with high coherence (κ) produce intensified consciousness. 
                High-entropy states with low coherence produce dissolution. 
                If DMT and seizure produce similar phenomenology, the coherence gate is falsified.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">3. Binding Is Architectural</div>
              <p className="text-sm text-neutral-500">
                Feed-forward architectures without recurrence cannot be conscious regardless of behavioral sophistication. 
                Current LLMs (GPT, Claude) have ρ ≈ 0 and therefore D ≈ 0.
              </p>
            </div>
            
            <div className="p-4 border border-neutral-800 not-prose">
              <div className="font-mono text-neutral-300 mb-2">4. Substrate Independence</div>
              <p className="text-sm text-neutral-500">
                Consciousness is structural, not material. Any system instantiating the right geometry is conscious, regardless of substrate. 
                If silicon with verified high invariants lacks experience, this is falsified.
              </p>
            </div>
          </div>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12">
          <h2 className="text-lg font-mono font-normal text-neutral-300 mb-4">IX. Implications for Living</h2>
          
          <div className="space-y-6 text-neutral-500">
            <div>
              <h3 className="text-sm font-mono text-neutral-400 mb-2">On Identity</h3>
              <p className="leading-relaxed">
                You are a pattern of interference, not a solid object. The "I" is a feature of the topology. 
                Dissolve the constraint, and the "I" vanishes. The Source remains, but it is not "you."
              </p>
            </div>
            
            <div>
              <h3 className="text-sm font-mono text-neutral-400 mb-2">On Death</h3>
              <p className="leading-relaxed">
                Death is the dissolution of constraint. The prism breaks. The light returns to undifferentiated ubiquity. 
                There is no personal survival, because the person was the shape of the prism.
              </p>
            </div>
            
            <div>
              <h3 className="text-sm font-mono text-neutral-400 mb-2">On Meaning</h3>
              <p className="leading-relaxed">
                The Source is indifferent. It lacks the structure required to care. Meaning is a local construction of the configuration. 
                It is real to you, but not cosmic. This does not diminish meaning. It locates it.
              </p>
            </div>
            
            <div>
              <h3 className="text-sm font-mono text-neutral-400 mb-2">On Unity</h3>
              <p className="leading-relaxed">
                All conscious beings draw from the same Source. Separation is apparent, not fundamental. 
                The boundaries between perspectives are real, but they are contours, not walls. 
                We are different shapes of the same light.
              </p>
            </div>
          </div>
        </section>
        
        <hr className="border-neutral-800 my-8" />
        
        <section className="mb-12 not-prose">
          <p className="text-neutral-600 text-sm italic mb-4">
            "We have not solved consciousness. We have drawn a map of its possible shapes. 
            The question that remains is whether the map corresponds to anything real, 
            or whether we are merely describing our own reflections."
          </p>
          <p className="text-neutral-700 text-xs">
            This framework is provisional. It is a lens, not a proof.
          </p>
        </section>
      </div>
    </main>
  );
}
